{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cc4da89a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app '__main__'\n",
      " * Debug mode: on\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\n",
      " * Running on http://127.0.0.1:5000\n",
      "Press CTRL+C to quit\n",
      " * Restarting with stat\n"
     ]
    },
    {
     "ename": "SystemExit",
     "evalue": "1",
     "output_type": "error",
     "traceback": [
      "An exception has occurred, use %tb to see the full traceback.\n",
      "\u001b[31mSystemExit\u001b[39m\u001b[31m:\u001b[39m 1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Pc\\AppData\\Roaming\\Python\\Python314\\site-packages\\IPython\\core\\interactiveshell.py:3783: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.\n",
      "  warn(\"To exit: use 'exit', 'quit', or Ctrl-D.\", stacklevel=1)\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "from PIL import Image\n",
    "import torchvision.transforms as transforms\n",
    "from flask import Flask, render_template, request\n",
    "\n",
    "# ==========================================\n",
    "# 1. DEFINICIÓN DEL ALFABETO EN ESPAÑOL\n",
    "# ==========================================\n",
    "# Alfabeto adaptado a la escritura en español para pruebas SisAT\n",
    "ALFABETO_ESPANOL = (\n",
    "    \"abcdefghijklmnopqrstuvwxyz\"\n",
    "    \"ABCDEFGHIJKLMNOPQRSTUVWXYZ\"\n",
    "    \"0123456789\"\n",
    "    \"áéíóúÁÉÍÓÚñÑ\"\n",
    "    \".,¿?¡! \"\n",
    ")\n",
    "\n",
    "class HTRDecoder:\n",
    "    \"\"\"Maneja el mapeo de caracteres y la decodificación CTC para palabras.\"\"\"\n",
    "    def __init__(self, alphabet):\n",
    "        self.alphabet = alphabet + \"-\"  # '-' representa el token 'blank' para CTC\n",
    "        self.char2idx = {char: idx for idx, char in enumerate(self.alphabet)}\n",
    "        self.idx2char = {idx: char for idx, char in enumerate(self.alphabet)}\n",
    "        self.blank_idx = len(self.alphabet) - 1\n",
    "\n",
    "    def decode_greedy(self, preds):\n",
    "        \"\"\"\n",
    "        Decodificación codiciosa (Greedy Search):\n",
    "        Toma el carácter de mayor probabilidad en cada paso de tiempo,\n",
    "        colapsa caracteres repetidos consecutivos y remueve el token 'blank'.\n",
    "        \"\"\"\n",
    "        # preds shape: [time_steps, batch_size, num_classes]\n",
    "        arg_maxes = torch.argmax(preds, dim=2).permute(1, 0)  # [batch_size, time_steps]\n",
    "        \n",
    "        decoded_strings = []\n",
    "        for seq in arg_maxes:\n",
    "            char_list = []\n",
    "            for i in range(len(seq)):\n",
    "                if seq[i] != self.blank_idx and (i == 0 or seq[i] != seq[i-1]):\n",
    "                    char_list.append(self.idx2char[seq[i].item()])\n",
    "            decoded_strings.append(\"\".join(char_list))\n",
    "            \n",
    "        return decoded_strings\n",
    "\n",
    "# ==========================================\n",
    "# 2. ARQUITECTURA CRNN (CNN + BiLSTM + FC)\n",
    "# ==========================================\n",
    "class CRNN_Palabras(nn.Module):\n",
    "    def __init__(self, num_classes, img_height=32):\n",
    "        super(CRNN_Palabras, self).__init__()\n",
    "        \n",
    "        # Extractor de características visuales (CNN)\n",
    "        self.cnn = nn.Sequential(\n",
    "            nn.Conv2d(1, 64, kernel_size=3, padding=1),\n",
    "            nn.BatchNorm2d(64),\n",
    "            nn.ReLU(True),\n",
    "            nn.MaxPool2d(2, 2),  # 32xW -> 16x(W/2)\n",
    "            \n",
    "            nn.Conv2d(64, 128, kernel_size=3, padding=1),\n",
    "            nn.BatchNorm2d(128),\n",
    "            nn.ReLU(True),\n",
    "            nn.MaxPool2d(2, 2),  # 16x(W/2) -> 8x(W/4)\n",
    "            \n",
    "            nn.Conv2d(128, 256, kernel_size=3, padding=1),\n",
    "            nn.BatchNorm2d(256),\n",
    "            nn.ReLU(True),\n",
    "            \n",
    "            nn.Conv2d(256, 256, kernel_size=3, padding=1),\n",
    "            nn.BatchNorm2d(256),\n",
    "            nn.ReLU(True),\n",
    "            nn.MaxPool2d((2, 1), (2, 1)),  # 8x(W/4) -> 4x(W/4)\n",
    "            \n",
    "            nn.Conv2d(256, 512, kernel_size=3, padding=1),\n",
    "            nn.BatchNorm2d(512),\n",
    "            nn.ReLU(True),\n",
    "            nn.MaxPool2d((2, 1), (2, 1)),  # 4x(W/4) -> 2x(W/4)\n",
    "            \n",
    "            nn.Conv2d(512, 512, kernel_size=2, padding=0),  # 2x(W/4) -> 1x(W/4 - 1)\n",
    "            nn.BatchNorm2d(512),\n",
    "            nn.ReLU(True)\n",
    "        )\n",
    "        \n",
    "        # Red Recurrente Bidireccional (BiLSTM)\n",
    "        self.rnn = nn.LSTM(\n",
    "            input_size=512,\n",
    "            hidden_size=256,\n",
    "            num_layers=2,\n",
    "            bidirectional=True,\n",
    "            batch_first=False\n",
    "        )\n",
    "        \n",
    "        # Capa de proyección a las clases del vocabulario\n",
    "        self.fc = nn.Linear(256 * 2, num_classes)\n",
    "\n",
    "    def forward(self, x):\n",
    "        # x: [batch, 1, 32, width]\n",
    "        features = self.cnn(x)              # [batch, 512, 1, width_reduced]\n",
    "        features = features.squeeze(2)      # [batch, 512, width_reduced]\n",
    "        features = features.permute(2, 0, 1) # [width_reduced (time_steps), batch, 512]\n",
    "        \n",
    "        rnn_out, _ = self.rnn(features)    # [time_steps, batch, 512]\n",
    "        outputs = self.fc(rnn_out)          # [time_steps, batch, num_classes]\n",
    "        return outputs\n",
    "\n",
    "# ==========================================\n",
    "# 3. PREPROCESAMIENTO DE LA PALABRA\n",
    "# ==========================================\n",
    "def preprocesar_palabra(ruta_imagen, img_height=32):\n",
    "    \"\"\"\n",
    "    Carga la imagen, la convierte a escala de grises, redimensiona\n",
    "    manteniendo la relación de aspecto a altura 32 y la convierte a Tensor.\n",
    "    \"\"\"\n",
    "    imagen = Image.open(ruta_imagen).convert('L') # Escala de grises\n",
    "    w, h = imagen.size\n",
    "    \n",
    "    # Redimensionar manteniendo proporción (altura fija de 32px)\n",
    "    nuevo_ancho = max(int(w * (img_height / float(h))), 32)\n",
    "    imagen = imagen.resize((nuevo_ancho, img_height), Image.Resampling.LANCZOS)\n",
    "    \n",
    "    # Transformar a Tensor PyTorch y normalizar a [-1, 1]\n",
    "    transform = transforms.Compose([\n",
    "        transforms.ToTensor(),\n",
    "        transforms.Normalize(mean=[0.5], std=[0.5])\n",
    "    ])\n",
    "    \n",
    "    tensor_img = transform(imagen).unsqueeze(0) # [1, 1, 32, W]\n",
    "    return tensor_img\n",
    "\n",
    "# ==========================================\n",
    "# 4. CONFIGURACIÓN DE FLASK Y MODELO\n",
    "# ==========================================\n",
    "app = Flask(__name__)\n",
    "UPLOAD_FOLDER = \"static/uploads\"\n",
    "os.makedirs(UPLOAD_FOLDER, exist_ok=True)\n",
    "app.config[\"UPLOAD_FOLDER\"] = UPLOAD_FOLDER\n",
    "\n",
    "# Inicializar decodificador y modelo CRNN\n",
    "decoder = HTRDecoder(ALFABETO_ESPANOL)\n",
    "num_classes = len(decoder.alphabet)\n",
    "model = CRNN_Palabras(num_classes=num_classes, img_height=32)\n",
    "\n",
    "# Si tienes un archivo de pesos (.pth) entrenado, se cargaría aquí:\n",
    "# model.load_state_dict(torch.load(\"pesos_crnn_palabras.pth\", map_location='cpu'))\n",
    "model.eval()\n",
    "\n",
    "def reconocer_palabra(ruta_imagen):\n",
    "    tensor_img = preprocesar_palabra(ruta_imagen)\n",
    "    with torch.no_grad():\n",
    "        preds = model(tensor_img)\n",
    "        palabra_reconocida = decoder.decode_greedy(preds)[0]\n",
    "    return palabra_reconocida\n",
    "\n",
    "@app.route(\"/\", methods=[\"GET\", \"POST\"])\n",
    "def index():\n",
    "    texto = None\n",
    "    imagen_url = None\n",
    "\n",
    "    if request.method == \"POST\":\n",
    "        if \"imagen\" not in request.files or request.files[\"imagen\"].filename == \"\":\n",
    "            return render_template(\"index.html\", error=\"No se seleccionó ninguna imagen de palabra.\")\n",
    "\n",
    "        archivo = request.files[\"imagen\"]\n",
    "        ruta = os.path.join(app.config[\"UPLOAD_FOLDER\"], archivo.filename)\n",
    "        archivo.save(ruta)\n",
    "        \n",
    "        imagen_url = f\"uploads/{archivo.filename}\"\n",
    "\n",
    "        try:\n",
    "            texto = reconocer_palabra(ruta)\n",
    "        except Exception as e:\n",
    "            return render_template(\"index.html\", error=f\"Error procesando la palabra: {e}\")\n",
    "\n",
    "    return render_template(\"index.html\", texto=texto, imagen_url=imagen_url)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    app.run(host=\"127.0.0.1\", port=5000, debug=True, use_reloader=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
